johalun/sysctl-rs

- Cargo.toml
- src/lib.rs
This PR introduces the [failure](https://crates.io/crates/failure) crate using the [Custom Fail Type Pattern](https://boats.gitlab.io/failure/custom-fail.html), allowing to match on SysctlError variants.
> Introduce failure

- src/lib.rs
The `oidfmt` sysctl may return less than 2 bytes of format. In this case,
`CtlInfo.is_temperature()` would panic.
Instead of comparing the slice `self.fmt[0..2]` to `"IK"`, we now use
`self.fmt.starts_with("IK")`, which handles shorter strings gracefully.
The following program panics on FreeBSD:
```rust
extern crate sysctl;
fn main() {
let value = sysctl::value("kern.ipc.shmsegs");
println!("kern.ipc.shmsegs: {:?}", value);
}
```
> oidfmt: Fix panic in CtlInfo.is_temperature()

- examples/iterate.rs
- src/lib.rs
Work in Progress, builds on (merge these first)
Fixes #3
- Remove major roadblocks for iterating over controls
- examples
> Struct interface

- Cargo.toml
- README.md
- examples/set_value.rs
- examples/struct.rs
- examples/temperature.rs
- examples/value.rs
- examples/value_as.rs
- examples/value_oid_as.rs
- src/lib.rs
* needed to expose the OID for the value_oid_as example, so there's a use case for this.
* fixes #10, and also restores hw.usb.debug to the original value. Hide some of the docstest setup and teardown code from the examples.
* as discussed on IRC, add myself to the authors
> Update examples and expose the OID

- src/lib.rs
The set_value tests require root access and therefore fail when run as
an unprivileged user. Therefore check if we are root first.
Fixes #16.
> tests: check if root before setting values

- src/lib.rs
If a sysctl does not exist, return the more specific
`SysctlError::NotFound` wrapping the sysctl name.
> errors: more specific error if sysctl not found

- src/lib.rs
One way of implementing #18.
~~This wasn't tested on macos.~~
If you do decide to merge this, it would be great if you could then also bump the version and publish 0.3.0 to crates.io :)
> publish CtlInfo struct

- examples/value.rs
- examples/value_string.rs
- src/ctl_value.rs
- src/temperature.rs
- src/unix/ctl.rs
- src/unix/funcs.rs
This is a purely mechanical change to replace try! with ?, since try! generates a warning on newer rustc.
Also ran cargo fmt, which did some unrelated whitespace tidying.
Tested on FreeBSD 12.
> Replace deprecated try! with ?

- src/ctl_value.rs
- src/temperature.rs
- src/unix/funcs.rs
CTLTYPE_S64 is a signed integer, but the value declaration makes it unsigned.
Relevant FreeBSD src: https://github.com/freebsd/freebsd/blob/master/sys/sys/sysctl.h#L73
Tested on FreeBSD 12, but I think I found all the S64 instances in the other supported platforms. The size calculation in min_type_size() already used i64.
> S64 is a signed integer.

- src/ctl_type.rs
- src/ctl_value.rs
- src/lib.rs
- src/linux/ctl_iter.rs
- src/temperature.rs
- src/traits.rs
- src/unix/ctl_iter.rs
Remove unneeded extern lines while there. Also add convenience method to get CtlType from CtlValue.
Some of the doc examples no longer compiled, so were misleading examples. This diff removes all the 'ignore' annotations from the doc examples and makes them compile and pass on FreeBSD 12 and Ubuntu 20.
> Fix doc examples.

- Cargo.toml
- src/ctl_error.rs
- src/lib.rs
As said in title, `failure` is now depracated and there is a suggestion to convert to `thiserror`.
> Replace depracated failure crate with thiserror

- src/ctl_type.rs
- src/temperature.rs
- src/traits.rs
- src/unix/ctl.rs
- src/unix/ctl_iter.rs
- src/unix/funcs.rs
This PR fixes a few issues reported by `cargo clippy`.
We exclude lints in various places:
- `needless_doctest_main` so that we don't change the documentation
- `redundant_field_names` so we don't end up with mixed style struct instantiations
These changes were made on FreeBSD and the test suite passes there. I don't currently have access to Linux or macOS, but could test there later if needed.
> Fixes clippy lints

- .cirrus.yml
- Cargo.toml
Needs thiserror 1.0.2 or later for #[from]
Check minver in CI.
> Fix the build with minimally-specified dependencies

- Cargo.toml
This reduces the size of the crate download by 98%, before compression.
> Don't include docs in the package

- .cirrus.yml
This should fix CI's pkg errors
> Update the FreeBSD CI images to currently supported releases

- .cirrus.yml
Cirrus no longer supports either Mojave or High Sierra
Fixes #42
> Update OSX VM for CI

- src/unix/ctl.rs
This addresses issue #46 where it seems to be that a `println!` for debugging has been left behind, affecting at least FreeBSD.
> Remove debugging println that is visible on FreeBSD

- src/lib.rs
Just noticed in the docs that the `str_value` was never used.
> Fix the string value example

- src/unix/funcs.rs
It's possible for sysctl call to return fewer bytes than expected, in which case we just truncate the bytes to the reported length.
> Don't error out on truncated values

- README.md
- src/ctl_error.rs
- src/ctl_flags.rs
- src/ctl_value.rs
- src/lib.rs
- src/unix/ctl.rs
- src/unix/funcs.rs
Add iOS as a target, which shares the same code base as Mac OS.
> add iOS as a supported target

- examples/value_oid_as.rs
- src/ctl_error.rs
- src/linux/ctl.rs
- src/traits.rs
- src/unix/ctl.rs
- src/unix/ctl_iter.rs
- src/unix/funcs.rs
sysctl-rs makes extensive use of sysctl oidfmt to look up the type and format of sysctls. Unfortunately, this is not allowed on non-jailbroken iOS as any such calls return `-EPERM`. Instead, we should be using `sysctlbyname` on iOS, which means that we are way more restricted since we cannot look up the type or format, and as such the user will have to provide these for full iOS support. In addition, the original implementation does work on jailbroken iOS, so we want to keep that option available (e.g. you could first try using `Ctl::new()` and then fallback to `Ctl::new_with_type()` to support both).
This PR changes the following things:
- `Ctl` in `unix.rs` is now an enum that either contains the oid or the name + type + format string.
- `Ctl` in `unix.rs` implements `oid()` to return a …
> implement variant of Ctl that strictly uses sysctlbyname

- CHANGELOG.md
- Cargo.toml
- examples/struct.rs
- examples/temperature.rs
- src/ctl_value.rs
- src/lib.rs
- src/temperature.rs
For example, these methods shorten
```rust
if let CtlValue::Temperature(t) = value {
...
}
```
into
```rust
let t = value.as_temperature().unwrap();
```
> Add accessor methods for destructuring CtlValue

- CHANGELOG.md
- Cargo.toml
This elminates a double dependency on both syn-1 and syn-2
> Update enum-as-inner to 0.6.0

- Cargo.toml
- src/ctl_flags.rs
From https://github.com/bitflags/bitflags/releases/tag/2.0.0 the only breaking change appears to be on .bits
> Update bitflags to v2

- .cirrus.yml
Because enum-as-inner no longer builds with -Zminimal-versions on recent nightlies.
> During CI, use -Zdirect-minimal-versions instead of -Zminimal-versions

- src/ctl_error.rs
- src/ctl_flags.rs
- src/ctl_type.rs
- src/ctl_value.rs
- src/lib.rs
- src/unix/ctl.rs
- src/unix/funcs.rs
This commit extends platform support to include tvOS and visionOS alongside existing macOS and iOS targets. Specifically:
- Updated conditional compilation flags to include `target_os = "tvos"` and `target_os = "visionos"` where appropriate
- Expanded platform-specific code paths to handle these new targets
- Ensured consistent behavior across all Apple platforms (macOS, iOS, tvOS, visionOS)
This change allows the sysctl crate to be used on a wider range of Apple devices and platforms while maintaining existing functionality.
> Add support for tvOS and visionOS platforms
